{
 "title": "Activiti Cloud Process Simulator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pg_dataSource", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Completed task by HR users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_date,$__interval),\n  assignee AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM task\nWHERE\n  $__timeFilter(completed_date) AND\n  assignee IN ('hr_user_1','hr_user_2','hr_user_3')\nGROUP BY 1, assignee,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Completed task by assignee",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_date,1y),\n  assignee AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM task\nWHERE\n  $__timeFilter(completed_date) AND\n  status = 'COMPLETED'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Completed process instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_date,$__interval),\n  status AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM process_instance\nWHERE\n  $__timeFilter(completed_date) AND\n  status = 'COMPLETED'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Completed task by TECH users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_date,$__interval),\n  assignee AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM task\nWHERE\n  $__timeFilter(completed_date) AND\n  assignee IN ('tech_user_1','tech_user_2')\nGROUP BY 1, assignee,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Active task by type",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_date,1y),\n  name AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM task\nWHERE\n  $__timeFilter(created_date) AND\n  status = 'CREATED'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Completed task by HR Manager",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_date,$__interval),\n  assignee AS metric,\n  count(process_definition_version) AS \"process_definition_version\"\nFROM task\nWHERE\n  $__timeFilter(completed_date) AND\n  assignee IN ('hr_manager')\nGROUP BY 1, assignee,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}